default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fbsns_development

test:
  <<: *default
  database: fbsns_test

production:
  <<: *default
  database: fbsns_production
  username: fbsns
  password: <%= ENV['FBSNS_DATABASE_PASSWORD'] %>
